export { default as ManagerHeader } from './ManagerHeader'
export { default as ManagerNavigation } from './ManagerNavigation'
export { default as OverviewTab } from './tabs/OverviewTab'
export { default as AnalyticsTab } from './tabs/AnalyticsTab'
export { default as TrainingTab } from './tabs/TrainingTab'
export { default as AchievementsTab } from './tabs/AchievementsTab'
export { default as DevelopmentTab } from './tabs/DevelopmentTab'
export { default as SettingsTab } from './tabs/SettingsTab'
export { default as EnhancedManagerDashboard } from './EnhancedManagerDashboard'
export type { TeamMember, TeamMetrics, TrainingModule, ManagerTab, ManagerPageProps } from './types'